// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aes_ige_encrypt
RawVector aes_ige_encrypt(RawVector key_raw, RawVector iv_raw, RawVector data_raw);
RcppExport SEXP _telegramR_aes_ige_encrypt(SEXP key_rawSEXP, SEXP iv_rawSEXP, SEXP data_rawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type key_raw(key_rawSEXP);
    Rcpp::traits::input_parameter< RawVector >::type iv_raw(iv_rawSEXP);
    Rcpp::traits::input_parameter< RawVector >::type data_raw(data_rawSEXP);
    rcpp_result_gen = Rcpp::wrap(aes_ige_encrypt(key_raw, iv_raw, data_raw));
    return rcpp_result_gen;
END_RCPP
}
// aes_ige_decrypt
RawVector aes_ige_decrypt(RawVector key_raw, RawVector iv_raw, RawVector data_raw);
RcppExport SEXP _telegramR_aes_ige_decrypt(SEXP key_rawSEXP, SEXP iv_rawSEXP, SEXP data_rawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type key_raw(key_rawSEXP);
    Rcpp::traits::input_parameter< RawVector >::type iv_raw(iv_rawSEXP);
    Rcpp::traits::input_parameter< RawVector >::type data_raw(data_rawSEXP);
    rcpp_result_gen = Rcpp::wrap(aes_ige_decrypt(key_raw, iv_raw, data_raw));
    return rcpp_result_gen;
END_RCPP
}
// pack_int64
RawVector pack_int64(SEXP x);
RcppExport SEXP _telegramR_pack_int64(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pack_int64(x));
    return rcpp_result_gen;
END_RCPP
}
// unpack_int64
double unpack_int64(RawVector raw_vector);
RcppExport SEXP _telegramR_unpack_int64(SEXP raw_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type raw_vector(raw_vectorSEXP);
    rcpp_result_gen = Rcpp::wrap(unpack_int64(raw_vector));
    return rcpp_result_gen;
END_RCPP
}
// xor_bytes
RawVector xor_bytes(RawVector a, RawVector b);
RcppExport SEXP _telegramR_xor_bytes(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< RawVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(xor_bytes(a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_telegramR_aes_ige_encrypt", (DL_FUNC) &_telegramR_aes_ige_encrypt, 3},
    {"_telegramR_aes_ige_decrypt", (DL_FUNC) &_telegramR_aes_ige_decrypt, 3},
    {"_telegramR_pack_int64", (DL_FUNC) &_telegramR_pack_int64, 1},
    {"_telegramR_unpack_int64", (DL_FUNC) &_telegramR_unpack_int64, 1},
    {"_telegramR_xor_bytes", (DL_FUNC) &_telegramR_xor_bytes, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_telegramR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
